In [11]:
import numpy as np

In [5]:
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(3,)


In [7]:
import time
import sys

In [3]:
b=range(1000)
print(sys.getsizeof(b[0])*len(b))
print(len(b))

24000
1000


In [16]:
c=np.arange(1000)
print(c.size*c.itemsize)

4000


In [9]:
b=np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
size=10000

In [12]:
L1=range(size)
L2=range(size)
A1=np.arange(size)
A2=np.arange(size)

In [13]:
start=time.time()
result=[(x+y) for x,y in zip(L1,L2)]
print("python list took:",(time.time()-start))

python list took: 0.0021719932556152344


In [18]:
start=time.time()
result=A1+A2
print("python numpy array took:",(time.time()-start))

python numpy array took: 0.003000020980834961


In [20]:
a=np.array([[1,2],[4,0],[3,9]])
print(a)

[[1 2]
 [4 0]
 [3 9]]


In [24]:
a.ndim

2

In [25]:
a.itemsize

4

In [27]:
a.shape

(3, 2)

In [28]:
a=np.array([[1,2],[4,0],[3,9]],dtype=np.float64)
print(a)

[[1. 2.]
 [4. 0.]
 [3. 9.]]


In [29]:
a.itemsize

8

In [30]:
a=np.array([[1,2],[4,0],[3,9]],dtype=np.complex64)
print(a)

[[1.+0.j 2.+0.j]
 [4.+0.j 0.+0.j]
 [3.+0.j 9.+0.j]]


In [35]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
l=range(5)
l

range(0, 5)

In [40]:
l=np.arange(5)
l

array([0, 1, 2, 3, 4])

In [41]:
print("concatenation example of array")
print(np.char.add(['hii','aman'],['gaurav','Maurya']))

concatenation example of array
['hiigaurav' 'amanMaurya']


In [42]:
print(np.char.multiply('gaurav',4))

gauravgauravgauravgaurav


In [43]:
print(np.char.center('Gaurav',25,fillchar='-'))

----------Gaurav---------


In [45]:
print(np.char.capitalize('he is doing great.'))

He is doing great.


In [47]:
print(np.char.upper(['hii','hellow']))
print(np.char.upper("hiii what's up!"))

['HII' 'HELLOW']
HIII WHAT'S UP!


In [49]:
print(np.char.lower(['HII','HELLow']))
print(np.char.lower("HMM YOU ARE GOOD AT IT."))

['hii' 'hellow']
hmm you are good at it.


In [50]:
print(np.char.split("are you coming to the party"))

['are', 'you', 'coming', 'to', 'the', 'party']


In [53]:
print(np.char.splitlines('hii \nlets move'))

['hii ', 'lets move']


In [56]:
print(np.char.join([':','-'],['hii ','come']))

['h:i:i: ' 'c-o-m-e']


In [58]:
print(np.char.strip(['are','aryan','arushi'],'a'))

['re' 'ryan' 'rushi']


In [59]:
print(np.char.replace('he is a good dancer.','is','was'))

he was a good dancer.
